# -*- coding: utf-8 -*-
"""nailedit chapter 3 assignment 1 1problem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MNMDzBEOQQZ2xCRCschEdB4foI_v2wnn

# Assignment 1 week 3 problem 1
"""

w = input ("enter the weight (Kgs) =")
w =int(w)
print (type(w))

x = input("enter the height in f or m")
x = str(x)
print (x)
comp = 'f'
com = 'F'

if comp or com == x:
    foot = input ("enter the height in feet")
    foot = int(foot)
    print (foot)
    inc = input ("enter the height in inch")
    inc =int(inc)
    print(inc)
    h = foot + (inc * 0.1)
    h =float(h)
    print(h)
    h = h/3.281
else:
    h = input ("enter height (Metres) =")
    h =float(h)
    print (type(h))

bmi = w/(h**2)
print (bmi)
if bmi < 18.5:
    print("under weight")
elif 18.5 <= bmi < 25:
    print("normal")
elif 25<= bmi < 30:
    print("over weight")
else:
    print("very over weight")

"""# Assignment 1 week 3 problem 2"""

nu = input ("enter the number ")
nu = int(nu)
print(nu)
f = '1'
f = int(f)
print(f)

for i in range(1,nu+1):
    f = f * i
print (f)